import { useState, useMemo, useCallback } from 'react'
import { DIAGNOSTICS } from './data/diagnostics.js'
import { inferDiagnosticScore, calculateReadinessScore, getReadinessBand, getRankedSections } from './logic/scoring.js'
import { selectInterventionPath, getStrengthsAndWeaknesses, buildNextActions } from './logic/pathing.js'
import IntakeForm from './components/IntakeForm.jsx'
import DiagnosticsWorkspace from './components/DiagnosticsWorkspace.jsx'
import ScorePanel from './components/ScorePanel.jsx'
import FinalReport from './components/FinalReport.jsx'
import LogicTrace from './components/LogicTrace.jsx'

const VIEWS = ['intake', 'diagnostics', 'report', 'trace']
const VIEW_LABELS = { intake: 'Intake', diagnostics: 'Diagnostics', report: 'Report', trace: 'Logic Trace' }

// This is a sample assessment for a fictional company, run through the tool's actual
// scoring and gating logic so the report below is a real computed output, not a mockup.
// It exists to show the tool working end to end without requiring a visitor to fill in
// their own data first. Use the tabs above to explore Diagnostics or Logic Trace, or
// edit any answer to see the report recompute live.
const DEFAULT_INTAKE = {
  companyName: 'Meridian Ops',
  operatorName: '',
  companyType: 'b2b_saas',
  companySummary: 'Illustrative example: a Series C workflow-automation platform for mid-market operations teams (~140 employees), evaluating where AI fits its product roadmap. Not a real client engagement.',
  notes: '',
  status: 'in_progress',
  hardGatingEnabled: true,
  evidenceRequired: false,
}

// Sample factor responses, generated by running one coherent company narrative (strong
// leadership and workflow clarity, weak data and governance maturity — a common pattern
// for a scaling B2B SaaS company) through every factor, then through the real
// scoring/pathing logic unmodified. See assessment/gen-sample.mjs for how these were
// derived.
const DEFAULT_FACTOR_RESPONSES = {
  l1: true, l2: false, l3: false, l4: true, l5: true, l6: true, l7: 4, l8: 4, l9: 5,
  w1: true, w2: true, w3: true, w4: true, w5: true, w6: true, w7: true, w8: 4, w9: 5,
  d1: false, d2: true, d3: true, d4: false, d5: 2, d6: 3, d7: 2, d8: false, d9: false, d10: true,
  u1: false, u2: false, u3: true, u4: true, u5: true, u6: 2, u7: 3, u8: 3,
  e1: false, e2: true, e3: false, e4: false, e5: true, e6: 4, e7: 3, e8: 4, e9: 4,
  g1: false, g2: true, g3: false, g4: false, g5: false, g6: false, g7: 2, g8: 2,
  m1: false, m2: true, m3: false, m4: true, m5: true, m6: 4, m7: 3,
  s1: false, s2: true, s3: true, s4: true, s5: 3, s6: 4, s7: 3,
}

export default function App() {
  const [view, setView] = useState('report')
  const [intake, setIntake] = useState(DEFAULT_INTAKE)
  const [factorResponses, setFactorResponses] = useState(DEFAULT_FACTOR_RESPONSES)
  const [sectionNotes, setSectionNotes] = useState({})

  const handleIntakeChange = useCallback((field, value) => {
    setIntake(prev => ({ ...prev, [field]: value }))
  }, [])

  const handleFactorChange = useCallback((factorId, value) => {
    setFactorResponses(prev => ({ ...prev, [factorId]: value }))
  }, [])

  const handleSectionNote = useCallback((sectionId, note) => {
    setSectionNotes(prev => ({ ...prev, [sectionId]: note }))
  }, [])

  const sectionScores = useMemo(() => {
    const result = {}
    for (const section of DIAGNOSTICS) {
      result[section.id] = inferDiagnosticScore(section.id, factorResponses)
    }
    return result
  }, [factorResponses])

  const readinessScore = useMemo(() => calculateReadinessScore(sectionScores), [sectionScores])
  const readinessBand = useMemo(() => getReadinessBand(readinessScore), [readinessScore])
  const rankedSections = useMemo(() => getRankedSections(sectionScores), [sectionScores])
  const pathResult = useMemo(() => selectInterventionPath(sectionScores, intake.hardGatingEnabled), [sectionScores, intake.hardGatingEnabled])
  const { strengths, weaknesses } = useMemo(() => getStrengthsAndWeaknesses(sectionScores), [sectionScores])
  const nextActions = useMemo(() => buildNextActions(pathResult, sectionScores), [pathResult, sectionScores])

  const hasIntake = Boolean(intake.companyName && intake.companyType)
  const answeredCount = Object.keys(factorResponses).filter(k => factorResponses[k] !== null && factorResponses[k] !== undefined).length
  const totalFactors = DIAGNOSTICS.flatMap(d => d.factorGroups.flatMap(g => g.factors)).length

  return (
    <div className="app-shell">
      <div className="sample-banner">
        <span>Illustrative example, not a real client engagement</span>
        <span style={{ marginLeft: 'auto' }}>
          <a href="../../case-studies.html#c4" style={{ color: 'inherit', textDecoration: 'underline' }}>← Back to portfolio</a>
        </span>
      </div>
      <header className="app-header">
        <div className="app-header-brand">
          <span className="brand-dot" />
          Austin Stretz · AI Readiness Assessment
        </div>
        <nav className="app-nav">
          {VIEWS.map(v => (
            <button
              key={v}
              className={`nav-btn${view === v ? ' active' : ''}`}
              onClick={() => setView(v)}
              disabled={v !== 'intake' && !hasIntake}
            >
              {VIEW_LABELS[v]}
            </button>
          ))}
        </nav>
        {hasIntake && (
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-3)' }}>
            {intake.companyName} · {answeredCount}/{totalFactors} factors
          </div>
        )}
      </header>

      <div className="app-body">
        <main className="main-content">
          {view === 'intake' && (
            <IntakeForm
              intake={intake}
              onChange={handleIntakeChange}
              onNext={() => setView('diagnostics')}
            />
          )}
          {view === 'diagnostics' && (
            <DiagnosticsWorkspace
              factorResponses={factorResponses}
              sectionNotes={sectionNotes}
              sectionScores={sectionScores}
              companyType={intake.companyType}
              onFactorChange={handleFactorChange}
              onSectionNote={handleSectionNote}
              onViewReport={() => setView('report')}
            />
          )}
          {view === 'report' && (
            <FinalReport
              intake={intake}
              sectionScores={sectionScores}
              readinessScore={readinessScore}
              readinessBand={readinessBand}
              pathResult={pathResult}
              strengths={strengths}
              weaknesses={weaknesses}
              nextActions={nextActions}
              sectionNotes={sectionNotes}
            />
          )}
          {view === 'trace' && (
            <LogicTrace
              sectionScores={sectionScores}
              factorResponses={factorResponses}
              pathResult={pathResult}
              readinessScore={readinessScore}
              readinessBand={readinessBand}
            />
          )}
        </main>

        {(view === 'diagnostics' || view === 'trace') && (
          <aside className="side-panel">
            <ScorePanel
              sectionScores={sectionScores}
              readinessScore={readinessScore}
              readinessBand={readinessBand}
              rankedSections={rankedSections}
              pathResult={pathResult}
              hardGatingEnabled={intake.hardGatingEnabled}
              onViewReport={() => setView('report')}
            />
          </aside>
        )}
      </div>
    </div>
  )
}
